# Generated by Django 4.2.6 on 2023-10-09 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=255, null=True)),
                ('item', models.CharField(max_length=255, null=True)),
                ('specification', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('verify_status', models.CharField(choices=[('PENDING', 'pending'), ('VERIFIED', 'verified'), ('REJECTED', 'rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verify_remarks', models.CharField(blank=True, help_text='Max length is 50 characters', max_length=50, null=True)),
                ('approve_status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='pending', max_length=20, null=True)),
                ('approval_at', models.DateTimeField(blank=True, null=True)),
                ('approval_remarks', models.CharField(blank=True, help_text='Max length is 50 characters', max_length=50, null=True)),
                ('final_approval_status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=20, null=True)),
                ('final_approval_at', models.DateTimeField(blank=True, null=True)),
                ('final_approval_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('finance_status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='PENDING', max_length=20, null=True)),
                ('finance_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('finance_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app.branch')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app.department')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='app.entity')),
                ('final_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_approved_quotations', to=settings.AUTH_USER_MODEL)),
                ('finance_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_user_quotations', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_quotations', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_quotations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='quotations_attachments/')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='app.quotation')),
            ],
        ),
    ]
